@startuml Class Biere
class Biere {
    - id int
    - name String
    - idMarque int
    - type TypeBiere
    - moyenne int
    - nbVotant int 
    - commentairs MutableList<Commentaire>
}

enum TypeBiere

class Commentaire {
    - idAuteur int
    - commentair String
}

TypeBiere - Biere
Commentaire "0..n" -- Biere
@enduml