@startuml Schema Objet

class Marque {
    - id int
    - name String
    - lieux MutableList<String>
    - biereProduit MutableList<Biere>
    - nbBiere int
    - description String
}

class Biere {
    - id int
    - name String
    - idMarque int
    - type TypeBiere
    - moyenne int
    - nbVotant int 
    - commentairs MutableList<Commentaire>
}

enum TypeBiere

class Commentaire {
    - idAuteur int
    - commentair String
}

TypeBiere - Biere
Commentaire "0..n" -- Biere

class Utilisateur {
    - id int
    - name String
    - mail String
    - biereListe MutableList<Biere>
}

Biere "1..n" --- "1" Marque
Utilisateur --- Biere

@enduml