version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}
              # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build

      - save_cache:
          paths: .gradle
          key: dependencies-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}