version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v3-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}
              # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build

      - save_cache:
          paths: ~/.gradle
          key: dependencies-v3-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}

  testUnitaire:
    executor: android/android

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v3-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Run Tests
          command: ./gradlew lint test

      - save_cache:
          paths: ~/.gradle
          key: dependencies-v3-{{ checksum "build.gradle" }}-{{ .Environment.CACHE_VERSION }}

      - store_artifacts:
          path: app/build/reports
          destination: reports
            - store_test_results:
                path: app/build/test-results


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - testUnitaire:
          requires:
            - build